In [1]:
# https://school.programmers.co.kr/learn/courses/30/lessons/60059

In [2]:
# 키는 자물쇠 배열보다 작아도 가능
# 키는 자물쇠 범위 밖으로도 나가도 괜찮다

In [3]:
import numpy as np

In [4]:
# 아래는 False가 나오는 문제임
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1,0], [1, 1, 0,1], [1, 0, 1,0],[1,0,0,1]]

In [5]:
# 자물쇠를 3배수로 확대 시킴 - > 실제로 필요한것은 자물쇠(4*4)에 한칸이라도 걸치게 늘리는게 맞을듯
# 12*12가 아닌 8*8로 해야 깔끔해진다. 하지만 숫자가 복잡해지니 일단 3배수로 편하게
n=len(lock)
lock_padding = [[0] * (n*3) for _ in range(n*3)]
for i in range(n):
    for j in range(n):
        lock_padding[i + n][j + n] = lock[i][j]
lock_padding

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [12]:
# 그냥 간편하게 크기가 같은 두 배열을 합쳐서 중앙에 실제 자물쇠에 해당하는 부분만 추출하는 방식을 선택
# 그래서 키도 자물쇠와 같은 크기의 배열을 만들었고, 키를 좌상단에서 우하단까지 이동시키면서 합치는 방법으로 진행했다.
# 첫번째 키의 형태 확인
key_padding = [[0] * (n*3) for _ in range(n*3)]
m=len(key)
for i in range(m):
    for j in range(m):
        key_padding[i][j] = key[i][j]
key_padding

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [8]:
# 키는 회전이 가능하다. 90도 회전하는 함수

def rotate_2d(list_2d):
    n = len(list_2d) # 행 길이 계산
    m = len(list_2d[0]) # 열 길이 계산
    new = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            new[j][n-i-1] = list_2d[i][j]
    return new

In [13]:
# 실제로 어떻게 되는지 확인.
# 자물쇠를 열수 있는지는, 가운데 자물쇠영역이 모두 1인지 확인하면 된다.
w=0
# 회전때문에 range를 4로 넣어줌
for _ in range(4):
    for z in range(3*n-(m-1)):
        key_padding = [[0] * (n*3) for _ in range(n*3)]
        
        # key_padding에 key를 넣는 코드. 단 이코드는 키를 오른쪽으로만 이동시킴
        for i in range(m):
            for j in range(m):
                key_padding[i][j+z] = key[i][j]

        for k in range(3*n-(m-1)):
            ans=[[c + d for c, d in zip(a, b)] for a, b in zip(key_padding,lock_padding)]
            # 자물쇠영역만 추출
            answer=np.array(ans)[n:2*n,n:2*n]

            print(f'시도{w}')
            print(np.array(ans),'\n')
            print(answer,'\n')
            # 자물쇠영역의 1의개수를 확인하는 코드
            print(np.count_nonzero(answer==1),'\n')
            
            
            # 다중 for 루프를 탈출하는 코드를 짜야했지만, 상관없어서 일단 진행
            if np.count_nonzero(answer==1) == 9:
                print(True)
                break
            
            w+=1
            
            # 위에서 key_padding에 넣은 key를 오른쪽으로만 이동이 가능했기 때문에
            # 하단으로 이동하는 코드를 추가했다.
            # insert로 상단에 [0]으로된 행을 추가하고, pop으로 하단 마지막줄을 제거했다.
            ins=len(key_padding)*[0]
            key_padding.insert(0,ins)
            key_padding.pop()
    key=rotate_2d(key)
    
    # 확인용 출력을 볼 수 있음

시도0
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 0 0 1]] 

10 

시도1
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 0]
 [1 1 0 1]
 [1 0 1 0]
 [1 0 0 1]] 

10 

시도2
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 

In [10]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1,0], [1, 1, 0,0], [1, 0, 1,0],[1,0,0,0]]


# 실제로 함수형태로 만들면, return을 중간에 넣으므로서, True일 경우를 빼내었다.

import numpy as np

def rotate_2d(list_2d):
    n = len(list_2d) # 행 길이 계산
    m = len(list_2d[0]) # 열 길이 계산
    new = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            new[j][n-i-1] = list_2d[i][j]
    return new

def solution(key, lock):
    m=len(key)
    n=len(lock)
    
    # 처음부터 자물쇠가 열려있는 경우를 우선 생각
    if np.count_nonzero(lock==1) == n**2:
        return True
    
    lock_padding = [[0] * (n*3) for _ in range(n*3)]
    for i in range(n):
        for j in range(n):
            lock_padding[i + n][j + n] = lock[i][j]
    w=0
    for _ in range(4):
        for z in range(3*n-(m-1)):
            key_padding = [[0] * (n*3) for _ in range(n*3)]
            for i in range(m):
                for j in range(m):
                    key_padding[i][j+z] = key[i][j]

            for k in range(3*n-(m-1)):
                ans=[[c + d for c, d in zip(a, b)] for a, b in zip(key_padding,lock_padding)]
                ans2=np.array(ans)[n:2*n,n:2*n]
                print(f'시도{w}')
                print(np.array(ans),'\n')
                print(ans2,'\n')
                print(np.count_nonzero(ans2==1),'\n')
                
                # 중간에 자물쇠가 풀리면 True로 함수를 끝냄
                if np.count_nonzero(ans2==1) == n**2:
                    return True
                
                w+=1
                ins=len(key_padding)*[0]
                key_padding.insert(0,ins)
                key_padding.pop()
        key=rotate_2d(key)
    return False


solution(key, lock)

시도0
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [1 0 0 0]] 

8 

시도1
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]] 

[[1 1 1 0]
 [1 1 0 0]
 [1 0 1 0]
 [1 0 0 0]] 

8 

시도2
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 1 1 1 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 

False

In [11]:
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1,0], [1, 1, 0,0], [1, 0, 1,0],[1,0,0,0]]


import numpy as np

def rotate_2d(list_2d):
    n = len(list_2d) # 행 길이 계산
    m = len(list_2d[0]) # 열 길이 계산
    new = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            new[j][n-i-1] = list_2d[i][j]
    return new

def solution(key, lock):

    m=len(key)
    n=len(lock)
    
    if np.count_nonzero(lock==1) == n**2:
        return True
    
    lock_padding = [[0] * (n*3) for _ in range(n*3)]
    for i in range(n):
        for j in range(n):
            lock_padding[i + n][j + n] = lock[i][j]

    for _ in range(4):
        for z in range(3*n-(m-1)):
            key_padding = [[0] * (n*3) for _ in range(n*3)]
            for i in range(m):
                for j in range(m):
                    key_padding[i][j+z] = key[i][j]

            for k in range(3*n-(m-1)):
                ans=[[c + d for c, d in zip(a, b)] for a, b in zip(key_padding,lock_padding)]
                answer=np.array(ans)[n:2*n,n:2*n]
                
                if np.count_nonzero(answer==1) == n**2:
                    return True
                
                ins=len(key_padding)*[0]
                key_padding.insert(0,ins)
                key_padding.pop()
        key=rotate_2d(key)
    return False


solution(key, lock)

False