In [1]:
# https://school.programmers.co.kr/learn/courses/30/lessons/92344

In [2]:
# N * M
# 적 공격 0 -> 파괴
# 아군 힐

# 건물 내구도 2차원 정수 배열 board
# 적의 공격 혹은 아군의 회복 스킬 2차원 정수 배열 skill
# 모두 끝난 뒤 파괴되지 않은 건물의 개수를 return
# 1 <= N <= 1000
# 1 <= M <= 1000
# 1 <= board 원소 <= 1000
# 1 <= skill 행 길이 <= 250000
# skill 열 길이 = 6
# skill의 각행 [type,r1,c1,r2,c2,degree]
# type = 1 공격 / type = 2 회복
# 0 <= r1,r2 < N
# 0 <= c1,c2 < M
# 1 <= degree <= 500


In [3]:
board = [[[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]],[[1,2,3],[4,5,6],[7,8,9]]]
skill = [[[1,0,0,3,4,4],[1,2,0,2,3,2],[2,1,0,3,1,2],[1,0,1,3,3,1]],[[1,1,1,2,2,4],[1,0,0,1,1,2],[2,2,0,2,0,100]]]

In [4]:
import numpy as np

board = [[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]]
skill = [[1,0,0,3,4,4],[1,2,0,2,3,2],[2,1,0,3,1,2],[1,0,1,3,3,1]]

board=np.array(board)
skill=np.array(skill)

board,skill

(array([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]),
 array([[1, 0, 0, 3, 4, 4],
        [1, 2, 0, 2, 3, 2],
        [2, 1, 0, 3, 1, 2],
        [1, 0, 1, 3, 3, 1]]))

In [5]:
for type,r1,c1,r2,c2,degree in skill:
    #print(type,r1,c1,r2,c2,degree)
    
    if type == 1 :
        for i in range(r1,r2+1):
            for j in range(c1,c2+1):
                board[i][j]+= degree*-1

    if type == 2 :
        for i in range(r1,r2+1):
            for j in range(c1,c2+1):
                board[i][j]+= degree

In [6]:
board

array([[ 1,  0,  0,  0,  1],
       [ 3,  2,  0,  0,  1],
       [ 1,  0, -2, -2,  1],
       [ 3,  2,  0,  0,  1]])

In [7]:
answer=np.count_nonzero(board>0)

In [8]:
import numpy as np

def solution(board, skill):
    answer = 0
    
    board=np.array(board)
    skill=np.array(skill)

    for type,r1,c1,r2,c2,degree in skill:
        #print(type,r1,c1,r2,c2,degree)
        
        if type == 1 :
            for i in range(r1,r2+1):
                for j in range(c1,c2+1):
                    board[i][j]+= degree*-1

        if type == 2 :
            for i in range(r1,r2+1):
                for j in range(c1,c2+1):
                    board[i][j]+= degree
                    
    answer=np.count_nonzero(board>0)
    
    return answer

board = [[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]]
skill = [[1,0,0,3,4,4],[1,2,0,2,3,2],[2,1,0,3,1,2],[1,0,1,3,3,1]]

solution(board,skill)

10

In [9]:
# 위 과정은 코딩테스트의 효율성검사를 통과하지 못함.
# 누적합을 이용한 방법을 사용해야함

In [10]:
# 누적합 관련 참조
# https://nahwasa.com/entry/%EB%88%84%EC%A0%81-%ED%95%A9prefix-sum-2%EC%B0%A8%EC%9B%90-%EB%88%84%EC%A0%81%ED%95%A9prefix-sum-of-matrix-with-java

In [5]:
import numpy as np

def solution(board, skill):
    answer = 0
    
    board=np.array(board)
    skill=np.array(skill)
    
    ps=np.array([[0 for j in range(len(board[0]) + 1)] for i in range(len(board) + 1)])
    
    for type,r1,c1,r2,c2,degree in skill:
        # 누적합 과정
        # 피해를 입는 경우
        if type == 1 :
            degree=-1*degree
            ps[r1][c1]+= degree
            ps[r1][c2+1]-= degree
            ps[r2+1][c1]-= degree
            ps[r2+1][c2+1]+= degree
        # 회복하는 경우
        if type == 2 :
            ps[r1][c1]+= degree
            ps[r1][c2+1]-= degree
            ps[r2+1][c1]-= degree
            ps[r2+1][c2+1]+= degree
    print('****************************************')
    print('before prefix-sum','\n',np.array(ps),'\n')

    # 행 누적 합    
    ps=ps.cumsum(axis=0)
    print('row prefix-sum','\n',np.array(ps),'\n')
    
    # 열 누적 합
    ps=ps.cumsum(axis=1)
    
    print('final prefix-sum(column sum)','\n',np.array(ps),'\n','\n','board','\n',board,'\n')
    # 두 배열의 원소를 각각 합치는 코드 [[1,1],[1,2]]+[[1,0],[0,0]]=[[2,1],[1,2]]
    ans=[[c + d for c, d in zip(a, b)] for a, b in zip(board,ps)]
    answer=np.count_nonzero(np.array(ans)>0)
    print('answer =',answer,'\n',np.array(ans),'\n')
    
    return answer

board = [[[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5],[5,5,5,5,5]],[[1,2,3],[4,5,6],[7,8,9]]]
skill = [[[1,0,0,3,4,4],[1,2,0,2,3,2],[2,1,0,3,1,2],[1,0,1,3,3,1]],[[1,1,1,2,2,4],[1,0,0,1,1,2],[2,2,0,2,0,100]]]

for i in [0,1]:
    b=board[i]
    s=skill[i]
    solution(b,s)

****************************************
before prefix-sum 
 [[-4 -1  0  0  1  4]
 [ 2  0 -2  0  0  0]
 [-2  0  0  0  2  0]
 [ 2  0  0  0 -2  0]
 [ 2  1  2  0 -1 -4]] 

row prefix-sum 
 [[-4 -1  0  0  1  4]
 [-2 -1 -2  0  1  4]
 [-4 -1 -2  0  3  4]
 [-2 -1 -2  0  1  4]
 [ 0  0  0  0  0  0]] 

final prefix-sum(column sum) 
 [[-4 -5 -5 -5 -4  0]
 [-2 -3 -5 -5 -4  0]
 [-4 -5 -7 -7 -4  0]
 [-2 -3 -5 -5 -4  0]
 [ 0  0  0  0  0  0]] 
 
 board 
 [[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 

answer = 10 
 [[ 1  0  0  0  1]
 [ 3  2  0  0  1]
 [ 1  0 -2 -2  1]
 [ 3  2  0  0  1]] 

****************************************
before prefix-sum 
 [[  -2    0    2    0]
 [   0   -4    0    4]
 [ 102 -100   -2    0]
 [-100  104    0   -4]] 

row prefix-sum 
 [[  -2    0    2    0]
 [  -2   -4    2    4]
 [ 100 -104    0    4]
 [   0    0    0    0]] 

final prefix-sum(column sum) 
 [[ -2  -2   0   0]
 [ -2  -6  -4   0]
 [100  -4  -4   0]
 [  0   0   0   0]] 
 
 board 
 [[1 2 3]
 [4 5 6]
 [7 8 9